name: satellogic2
channels:
- conda-forge
- defaults
dependencies:
- affine=2.2.0
- bleach=2.1.3
- bokeh=0.12.14
- boto3=1.6.7
- bzip2=1.0.6
- ca-certificates=2018.1.18
- cairo=1.14.10
- certifi=2018.1.18
- cffi=1.11.5
- chardet=3.0.4
- click=6.7
- click-plugins=1.0.3
- cligj=0.4.0
- cloudpickle=0.5.2
- cryptography=2.1.4
- cycler=0.10.0
- cytoolz=0.9.0.1
- dask=0.17.2
- dbus=1.10.22
- decorator=4.2.1
- distributed=1.21.4
- entrypoints=0.2.3
- expat=2.2.5
- fiona=1.7.11
- gdal=2.2.3
- geojson=2.3.0
- geos=3.6.2
- geotiff=1.4.2
- gettext=0.19.8.1
- ipython=6.2.1
- ipywidgets=7.1.2
- jinja2=2.10
- jupyter=1.0.0
- kealib=1.4.7
- kiwisolver=1.0.1
- krb5=1.14.2
- libgdal=2.2.3
- libiconv=1.15
- libkml=1.3.0
- locket=0.2.0
- matplotlib=2.2.2
- munch=2.2.0
- nbconvert=5.3.1
- nbformat=4.4.0
- networkx=2.1
- notebook=5.4.1
- numpy=1.14.2
- pandas=0.22.0
- pandoc=2.1.3
- pillow=5.0.0
- pixman=0.34.0
- proj4=4.9.3
- psutil=5.4.3
- pygments=2.2.0
- pyopenssl=17.5.0
- pyparsing=2.2.0
- pyqt=5.6.0
- pysal=1.14.3
- pysocks=1.6.8
- python=3.6.4
- python-dateutil=2.7.0
- pytz=2018.3
- pywavelets=0.5.2
- pyyaml=3.12
- pyzmq=17.0.0
- qt=5.6.2
- qtconsole=4.3.1
- rasterio=0.36.0
- readline=7.0
- requests=2.18.4
- s3transfer=0.1.13
- scikit-image=0.13.1
- scipy=1.0.0
- send2trash=1.5.0
- setuptools=39.0.1
- shapely=1.6.4
- simplegeneric=0.8.1
- sip=4.18
- six=1.11.0
- snuggs=1.4.1
- sortedcontainers=1.5.9
- spectral=0.19
- sqlite=3.20.1
- tblib=1.3.2
- terminado=0.8.1
- testpath=0.3.1
- tk=8.6.7
- toolz=0.9.0
- tornado=5.0.1
- traitlets=4.3.2
- urllib3=1.22
- wcwidth=0.1.7
- webencodings=0.5
- wheel=0.30.0
- widgetsnbextension=3.1.4
- yaml=0.1.7
- zeromq=4.2.3
- zict=0.1.3
- zlib=1.2.11
